const mongoose = require('mongoose');
const { Schema } = mongoose;

// ══════════════════════════════════════════════════════════════════════════════
// AI STUDY PLAN - Personalized daily study plans generated by AI
// ══════════════════════════════════════════════════════════════════════════════

const taskSchema = new Schema(
  {
    title: { type: String, required: true },
    subject: { type: String, required: true },
    duration: { type: Number, required: true }, // minutes
    priority: {
      type: String,
      enum: ['high', 'medium', 'low'],
      default: 'medium',
    },
    type: {
      type: String,
      enum: ['revision', 'practice', 'quiz', 'reading', 'video', 'break'],
      required: true,
    },
    description: { type: String },
    timeSlot: { type: String }, // e.g., "09:00-10:00"
    isCompleted: { type: Boolean, default: false },
    completedAt: { type: Date, default: null },
    order: { type: Number, default: 0 },
  },
  { _id: true }
);

const studyPlanSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    
    date: {
      type: Date,
      required: true,
      index: true,
    },
    
    // AI-generated content
    title: { type: String, required: true },
    summary: { type: String },
    motivationalMessage: { type: String },
    
    // Study tasks
    tasks: [taskSchema],
    totalTasks: { type: Number, default: 0 },
    completedTasks: { type: Number, default: 0 },
    
    // Time estimates
    totalDuration: { type: Number, default: 0 }, // total minutes
    estimatedStudyTime: { type: Number, default: 0 },
    
    // Progress
    progress: { type: Number, default: 0 }, // 0-100%
    isCompleted: { type: Boolean, default: false },
    completedAt: { type: Date, default: null },
    
    // Subjects covered
    subjects: [{ type: String }],
    
    // Focus areas
    focusAreas: [{ type: String }],
    
    // AI metadata
    generatedBy: {
      type: String,
      enum: ['ai', 'manual', 'template'],
      default: 'ai',
    },
    aiModel: { type: String, default: 'gpt-4' },
    aiPrompt: { type: String },
    
    // Status
    status: {
      type: String,
      enum: ['pending', 'in_progress', 'completed', 'skipped'],
      default: 'pending',
    },
  },
  {
    timestamps: true,
  }
);

// ══════════════════════════════════════════════════════════════════════════════
// INDEXES
// ══════════════════════════════════════════════════════════════════════════════

studyPlanSchema.index({ userId: 1, date: -1 });
studyPlanSchema.index({ date: 1 });
studyPlanSchema.index({ status: 1 });

// Compound index for finding user's plan for specific date
studyPlanSchema.index({ userId: 1, date: 1 }, { unique: true });

// ══════════════════════════════════════════════════════════════════════════════
// METHODS
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Mark task as completed
 */
studyPlanSchema.methods.completeTask = function (taskId) {
  const task = this.tasks.id(taskId);
  
  if (!task) {
    throw new Error('Task not found');
  }
  
  if (task.isCompleted) {
    return { alreadyCompleted: true };
  }
  
  task.isCompleted = true;
  task.completedAt = new Date();
  
  // Update completed count
  this.completedTasks = this.tasks.filter((t) => t.isCompleted).length;
  this.progress = (this.completedTasks / this.totalTasks) * 100;
  
  // Check if all tasks completed
  if (this.completedTasks === this.totalTasks) {
    this.isCompleted = true;
    this.completedAt = new Date();
    this.status = 'completed';
  } else if (this.completedTasks > 0) {
    this.status = 'in_progress';
  }
  
  return { 
    completed: true, 
    progress: this.progress,
    allTasksCompleted: this.isCompleted,
  };
};

/**
 * Add new task
 */
studyPlanSchema.methods.addTask = function (taskData) {
  this.tasks.push({
    ...taskData,
    order: this.tasks.length,
  });
  
  this.totalTasks = this.tasks.length;
  this.totalDuration = this.tasks.reduce((sum, t) => sum + t.duration, 0);
  
  // Update subjects list
  if (!this.subjects.includes(taskData.subject)) {
    this.subjects.push(taskData.subject);
  }
  
  // Recalculate progress
  this.completedTasks = this.tasks.filter((t) => t.isCompleted).length;
  this.progress = this.totalTasks > 0 ? (this.completedTasks / this.totalTasks) * 100 : 0;
};

/**
 * Remove task
 */
studyPlanSchema.methods.removeTask = function (taskId) {
  this.tasks.pull(taskId);
  this.totalTasks = this.tasks.length;
  this.totalDuration = this.tasks.reduce((sum, t) => sum + t.duration, 0);
  
  // Recalculate progress
  this.completedTasks = this.tasks.filter((t) => t.isCompleted).length;
  this.progress = this.totalTasks > 0 ? (this.completedTasks / this.totalTasks) * 100 : 0;
};

// ══════════════════════════════════════════════════════════════════════════════
// STATICS
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Get today's plan for user
 */
studyPlanSchema.statics.getTodaysPlan = function (userId) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  
  return this.findOne({
    userId,
    date: { $gte: today, $lt: tomorrow },
  });
};

/**
 * Get upcoming plans
 */
studyPlanSchema.statics.getUpcomingPlans = function (userId, days = 7) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  const futureDate = new Date(today);
  futureDate.setDate(futureDate.getDate() + days);
  
  return this.find({
    userId,
    date: { $gte: today, $lt: futureDate },
  }).sort({ date: 1 });
};

/**
 * Get completion stats for user
 */
studyPlanSchema.statics.getCompletionStats = async function (userId, days = 30) {
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - days);
  startDate.setHours(0, 0, 0, 0);
  
  const plans = await this.find({
    userId,
    date: { $gte: startDate },
  });
  
  const totalPlans = plans.length;
  const completedPlans = plans.filter((p) => p.isCompleted).length;
  const totalTasks = plans.reduce((sum, p) => sum + p.totalTasks, 0);
  const completedTasks = plans.reduce((sum, p) => sum + p.completedTasks, 0);
  const avgProgress = totalPlans > 0
    ? plans.reduce((sum, p) => sum + p.progress, 0) / totalPlans
    : 0;
  
  return {
    totalPlans,
    completedPlans,
    completionRate: totalPlans > 0 ? (completedPlans / totalPlans) * 100 : 0,
    totalTasks,
    completedTasks,
    taskCompletionRate: totalTasks > 0 ? (completedTasks / totalTasks) * 100 : 0,
    avgProgress,
  };
};

module.exports = mongoose.model('StudyPlan', studyPlanSchema);
